---
- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present

- name: Install Nginx
  apt: pkg=nginx state=latest update_cache=true
  notify:
   - Start Nginx

- name: Add H5BP Config
  copy: src=h5bp dest=/etc/nginx owner=root group=root

- name: Disable Default Config
  file: dest=/etc/nginx/sites-enabled/defalt state=absent
  notify:
    - Reload Nginx

- name: Add {{domain}} Site Config
  template: src=joaonzango.com.j2 dest=/etc/nginx/sites-available/{{ domain }} owner=root group=root

- name: Enable {{domain}} Site Config
  file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
  notify:
    - Reload Nginx
